# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/InputDlg.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InputDlg(object):
    def setupUi(self, InputDlg):
        InputDlg.setObjectName("InputDlg")
        InputDlg.resize(628, 532)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(InputDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(InputDlg)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.textMaterialSearch = QtWidgets.QLineEdit(InputDlg)
        self.textMaterialSearch.setObjectName("textMaterialSearch")
        self.verticalLayout_4.addWidget(self.textMaterialSearch)
        self.listWidgetMaterialLib = QtWidgets.QListWidget(InputDlg)
        self.listWidgetMaterialLib.setObjectName("listWidgetMaterialLib")
        self.verticalLayout_4.addWidget(self.listWidgetMaterialLib)
        self.pushButtonSaveMaterialLib = QtWidgets.QPushButton(InputDlg)
        self.pushButtonSaveMaterialLib.setObjectName("pushButtonSaveMaterialLib")
        self.verticalLayout_4.addWidget(self.pushButtonSaveMaterialLib)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonLoad = QtWidgets.QPushButton(InputDlg)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.verticalLayout_3.addWidget(self.pushButtonLoad)
        self.pushButtonSave = QtWidgets.QPushButton(InputDlg)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.verticalLayout_3.addWidget(self.pushButtonSave)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(InputDlg)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textMatName = QtWidgets.QPlainTextEdit(InputDlg)
        self.textMatName.setMinimumSize(QtCore.QSize(0, 25))
        self.textMatName.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textMatName.setObjectName("textMatName")
        self.verticalLayout.addWidget(self.textMatName)
        self.tableWidgetMatComposition = QtWidgets.QTableWidget(InputDlg)
        self.tableWidgetMatComposition.setObjectName("tableWidgetMatComposition")
        self.tableWidgetMatComposition.setColumnCount(2)
        self.tableWidgetMatComposition.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatComposition.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMatComposition.setHorizontalHeaderItem(1, item)
        self.tableWidgetMatComposition.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetMatComposition.verticalHeader().setVisible(False)
        self.tableWidgetMatComposition.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidgetMatComposition)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxSelectSpectra = QtWidgets.QComboBox(InputDlg)
        self.comboBoxSelectSpectra.setObjectName("comboBoxSelectSpectra")
        self.comboBoxSelectSpectra.addItem("")
        self.comboBoxSelectSpectra.addItem("")
        self.comboBoxSelectSpectra.addItem("")
        self.comboBoxSelectSpectra.addItem("")
        self.comboBoxSelectSpectra.addItem("")
        self.comboBoxSelectSpectra.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxSelectSpectra)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonShowResult = QtWidgets.QPushButton(InputDlg)
        self.pushButtonShowResult.setObjectName("pushButtonShowResult")
        self.horizontalLayout_3.addWidget(self.pushButtonShowResult)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(InputDlg)
        QtCore.QMetaObject.connectSlotsByName(InputDlg)

    def retranslateUi(self, InputDlg):
        _translate = QtCore.QCoreApplication.translate
        InputDlg.setWindowTitle(_translate("InputDlg", "Dialog"))
        self.label.setText(_translate("InputDlg", "Material Library:"))
        self.listWidgetMaterialLib.setToolTip(_translate("InputDlg", "<html><head/><body><p>This list contains currently cached materials, which can be found in the file in &quot;Data Save/matlist.txt&quot;, in which, each line represent one material\'s components.</p></body></html>"))
        self.pushButtonSaveMaterialLib.setText(_translate("InputDlg", "Save Material Library"))
        self.pushButtonLoad.setText(_translate("InputDlg", ">>>"))
        self.pushButtonSave.setText(_translate("InputDlg", "<<<"))
        self.label_2.setText(_translate("InputDlg", "Current Material"))
        item = self.tableWidgetMatComposition.horizontalHeaderItem(0)
        item.setText(_translate("InputDlg", "Nuclide"))
        item = self.tableWidgetMatComposition.horizontalHeaderItem(1)
        item.setText(_translate("InputDlg", "Weight Proportion (%)"))
        self.comboBoxSelectSpectra.setItemText(0, _translate("InputDlg", "1) "))
        self.comboBoxSelectSpectra.setItemText(1, _translate("InputDlg", "2) "))
        self.comboBoxSelectSpectra.setItemText(2, _translate("InputDlg", "3)"))
        self.comboBoxSelectSpectra.setItemText(3, _translate("InputDlg", "4)"))
        self.comboBoxSelectSpectra.setItemText(4, _translate("InputDlg", "5)"))
        self.comboBoxSelectSpectra.setItemText(5, _translate("InputDlg", "6)"))
        self.pushButtonShowResult.setText(_translate("InputDlg", "Show Activation Result"))

