# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/WidgetParam.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetParam(object):
    def setupUi(self, WidgetParam):
        WidgetParam.setObjectName("WidgetParam")
        WidgetParam.resize(523, 391)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(WidgetParam)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidgetDisplay = QtWidgets.QTabWidget(WidgetParam)
        self.tabWidgetDisplay.setObjectName("tabWidgetDisplay")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Data)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidgetParams = QtWidgets.QTableWidget(self.Data)
        self.tableWidgetParams.setObjectName("tableWidgetParams")
        self.tableWidgetParams.setColumnCount(5)
        self.tableWidgetParams.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetParams.setItem(6, 0, item)
        self.tableWidgetParams.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetParams.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidgetParams.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetParams.verticalHeader().setVisible(False)
        self.tableWidgetParams.verticalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.tableWidgetParams)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonSaveParam = QtWidgets.QPushButton(self.Data)
        self.pushButtonSaveParam.setObjectName("pushButtonSaveParam")
        self.horizontalLayout.addWidget(self.pushButtonSaveParam)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidgetDisplay.addTab(self.Data, "")
        self.Plot = QtWidgets.QWidget()
        self.Plot.setObjectName("Plot")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Plot)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.framePlot = QtWidgets.QFrame(self.Plot)
        self.framePlot.setMinimumSize(QtCore.QSize(0, 300))
        self.framePlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePlot.setObjectName("framePlot")
        self.verticalLayout_4.addWidget(self.framePlot)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonSavePlot = QtWidgets.QPushButton(self.Plot)
        self.pushButtonSavePlot.setObjectName("pushButtonSavePlot")
        self.horizontalLayout_2.addWidget(self.pushButtonSavePlot)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tabWidgetDisplay.addTab(self.Plot, "")
        self.horizontalLayout_3.addWidget(self.tabWidgetDisplay)

        self.retranslateUi(WidgetParam)
        self.tabWidgetDisplay.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WidgetParam)

    def retranslateUi(self, WidgetParam):
        _translate = QtCore.QCoreApplication.translate
        WidgetParam.setWindowTitle(_translate("WidgetParam", "Form"))
        item = self.tableWidgetParams.verticalHeaderItem(0)
        item.setText(_translate("WidgetParam", "1"))
        item = self.tableWidgetParams.verticalHeaderItem(1)
        item.setText(_translate("WidgetParam", "1E5"))
        item = self.tableWidgetParams.verticalHeaderItem(2)
        item.setText(_translate("WidgetParam", "1E6"))
        item = self.tableWidgetParams.verticalHeaderItem(3)
        item.setText(_translate("WidgetParam", "1E7"))
        item = self.tableWidgetParams.verticalHeaderItem(4)
        item.setText(_translate("WidgetParam", "1E8"))
        item = self.tableWidgetParams.verticalHeaderItem(5)
        item.setText(_translate("WidgetParam", "1E9"))
        item = self.tableWidgetParams.verticalHeaderItem(6)
        item.setText(_translate("WidgetParam", "1.5E9"))
        item = self.tableWidgetParams.horizontalHeaderItem(0)
        item.setText(_translate("WidgetParam", "Cooling (s)"))
        item = self.tableWidgetParams.horizontalHeaderItem(1)
        item.setText(_translate("WidgetParam", "Act (Bq/kg)"))
        item = self.tableWidgetParams.horizontalHeaderItem(2)
        item.setText(_translate("WidgetParam", "Heat (kW/kg)"))
        item = self.tableWidgetParams.horizontalHeaderItem(3)
        item.setText(_translate("WidgetParam", "Dose (Sv/h)"))
        item = self.tableWidgetParams.horizontalHeaderItem(4)
        item.setText(_translate("WidgetParam", "Ing (Sv/h)"))
        __sortingEnabled = self.tableWidgetParams.isSortingEnabled()
        self.tableWidgetParams.setSortingEnabled(False)
        item = self.tableWidgetParams.item(0, 0)
        item.setText(_translate("WidgetParam", "1.000"))
        item = self.tableWidgetParams.item(1, 0)
        item.setText(_translate("WidgetParam", "1.0E5"))
        item = self.tableWidgetParams.item(2, 0)
        item.setText(_translate("WidgetParam", "1.0E6"))
        item = self.tableWidgetParams.item(3, 0)
        item.setText(_translate("WidgetParam", "1.0E7"))
        item = self.tableWidgetParams.item(4, 0)
        item.setText(_translate("WidgetParam", "1.0E8"))
        item = self.tableWidgetParams.item(5, 0)
        item.setText(_translate("WidgetParam", "1.0E9"))
        item = self.tableWidgetParams.item(6, 0)
        item.setText(_translate("WidgetParam", "1.5E9"))
        self.tableWidgetParams.setSortingEnabled(__sortingEnabled)
        self.pushButtonSaveParam.setText(_translate("WidgetParam", "Save"))
        self.tabWidgetDisplay.setTabText(self.tabWidgetDisplay.indexOf(self.Data), _translate("WidgetParam", "Data"))
        self.pushButtonSavePlot.setText(_translate("WidgetParam", "Save"))
        self.tabWidgetDisplay.setTabText(self.tabWidgetDisplay.indexOf(self.Plot), _translate("WidgetParam", "Plot"))

